<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class PayslipResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'reference' => $this->reference,
            'employee' => $this->employee ? [
                'id' => $this->employee->id,
                'name' => $this->employee->full_name,
                'initials' => mb_substr((string) $this->employee->first_name, 0, 1).mb_substr((string) $this->employee->last_name, 0, 1),
            ] : null,
            'period' => sprintf('%04d-%02d', $this->period_year, $this->period_month),
            'period_year' => $this->period_year,
            'period_month' => $this->period_month,
            // Components written by the API; totals below are generated by
            // MySQL and cannot be set here.
            'basic_minor' => (int) $this->basic_minor,
            'overtime_minor' => (int) $this->overtime_minor,
            'bonus_minor' => (int) $this->bonus_minor,
            'allowance_minor' => (int) $this->allowance_minor,
            'tax_minor' => (int) $this->tax_minor,
            'pension_minor' => (int) $this->pension_minor,
            'other_deduction_minor' => (int) $this->other_deduction_minor,
            'gross_minor' => (int) $this->gross_minor,
            'total_deductions_minor' => (int) $this->total_deductions_minor,
            'net_minor' => (int) $this->net_minor,
            'currency' => $this->currency,
            'payment_method' => $this->payment_method,
            'status' => $this->status,
            'paid_at' => $this->paid_at?->toDateString(),
        ];
    }
}
